<html>
<head></head>
<body>
<div style="color: red; font-size: 14px; padding: 20px; margin: 0 auto; display: block; width:400px;">

    <?php if (isset($checkLogin) && $checkLogin) { ?>
        <h1> LOGIN alredy is used </h1>
    <? } ?>

    <?php if (isset($checkEmail) && $checkEmail) { ?>
        <h1> EMAIL alredy is used </h1>
    <? } ?>

    <?php if (isset($errors) && is_array($errors)): ?>
        <ul>
            <?php foreach ($errors as $error): ?>
                <li> - <?php echo $error; ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>

<form action="" method="post" class="form-login"
      style="display: block; width: 400px; margin: 0 auto;  padding: 20px; text-align: center;">
    <h2>
        <center>Registration
    </h2>
    </center><br>
    <input type="text" name="email" placeholder="E-mail" value=""/><br><br>
    <input type="text" name="login" placeholder="Login" value=""/><br><br>
    <input type="password" name="password" placeholder="Password" value=""/><br><br>
    <div class="os"></div>
    <input type="submit" name="submit" class="btn btn-default" style="width: 120px;" value="Register"/>
    <div class="os"></div>
</form>
</body>
</html>